esphome:
  name: ${name}
  on_boot:
    priority: -200
    then:
        - delay: ${onboot_valve_calibration_delay} #1min
        - script.execute: valve_maintenance

  project:
    name: "nliaudat.floor-heating-controller"
    version: "${revision}.dev"
  platformio_options:
    board_build.f_flash: 80000000L
    board_build.flash_mode: qio
    board_build.flash_size: 4MB
    
substitutions:
  #board and compilation
  board: esp32-s3-devkitc-1  # ESP32-S3 Mini / Super Mini compatible
  variant: esp32s3
  framework: esp-idf
  
  # https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/api-reference/peripherals/gpio.html
  # Pin definition for ESP32-S3 Mini
  # ADC1 channels: GPIO1-10 (ADC2 not usable with WiFi)
  sn74hc595_data_pin: GPIO6
  sn74hc595_clock_pin: GPIO7
  sn74hc595_latch_pin: GPIO15
  # sn74hc595_oe_pin: GPIO18 
  adc_bemf_1_pin: GPIO1
  adc_bemf_2_pin: GPIO2
  adc_bemf_3_pin: GPIO3
  adc_bemf_4_pin: GPIO4
  # adc_zero_calibration: "0.0"
  onewire_pin: GPIO5

esp32:
  board: ${board}
  variant: ${variant}
  framework:
    type: ${framework}
    version: recommended
    sdkconfig_options:
      CONFIG_COMPILER_OPTIMIZATION_SIZE: y

preferences:
  flash_write_interval: 60min
  

ota:
  - platform: esphome

safe_mode:


light:
  - platform: esp32_rmt_led_strip
    name: "${name} Status LED"
    id: ${id_prefix}status_led
    icon: "mdi:alarm-light"
    rgb_order: GRB
    pin: GPIO48
    num_leds: 1
    rmt_channel: 0
    chipset: ws2812
    restore_mode: ALWAYS_OFF

psram:
  mode: octal
  speed: 80MHz
